#!/bin/bash
#
# Script för att mounta mac diskar.
#
lsblk
read -r -p $'\x0aVilken disk ska mountas ' SRC1
echo -e '\n'
ls /mnt | grep "disk"
read -r -p $'\x0aVart ska den mountas? ' SRC2
mount -t hfs /dev/${SRC1} /mnt/${SRC2}; mount -t hfsplus /dev/${SRC1} /mnt/${SRC2}; apfs-fuse -o allow_other /dev/${SRC1} /mnt/${SRC2}
