#!/bin/bash

#
# Uppdaterat backupscript, slippa hårdkodningen av vilka mappar som behöver användas
#

MNTDIR="/mnt"

read -r -p $'\x0aMounta kunds disk source? y/n ' yn

if [[ $yn == "y" || $yn == "Y" ]]; then
    lsblk
    read -r -p $'\x0aVilken disk vill du mounta? ' SRC1

    echo -e "Vart ska kunds disk mountas? ex. disk1, disk2 o.sv. Reffar till /mnt/diskX\n"
    ls "${MNTDIR}"

    read -r -p $'\x0aVälj ett alternativ. ' SRC2

    select mpoint in "${SRC2}"; do
        case $mpoint in
            "${SRC2}") 
                ntfsfix /dev/$SRC1 ; mount /dev/$SRC1 /$MNTDIR/$SRC2
                break
            ;;
            "exit")
                exit
            ;;
        esac
    done

    read -r -p $'\x0aMounta upp backupserver? y/n ' jn

    if [[ $jn == "y" || $jn == "Y" ]]; then
#        lsblk
#        read -r -p "Vilken katalog ska vara destination? " DST1

#        echo -e "Välj vilken testrigg destination som ska mountas (dit backup kommer läggas)? \n"
#        echo -e "OBS! lösen för testriggarna är alina \n"
#        ls "${MNTDIR}/backupserver"

        read -r -p $'\x0aSkriv bara backup ' DST2

        select mpoint2 in "backup" ; do
            case $mpoint2 in
	    "backup")
	    	    mount -t cifs //10.120.20.80/backup /mnt/backupserver/ -o iocharset=utf8,user=backup
		    break
                ;;
                "exit")
                    exit
                ;;
            esac
        done
    fi 

elif [[ $yn == "n" || $yn == "N" ]]; then
    echo -e "Du valde att inte mounta någon disk, då antar vi att disk(arna) redan är mountade.\n
    Välj vilken katalog som är Source och vilken som är Destination.\n"

    ls "${MNTDIR}"
    read -r -p $'\x0avilken katalog är kunds disk mountad på? ' SRC2

    echo ""

    ls "${MNTDIR}"
    read -r -p $'\x0avilken katalog är destinations disken mountad på? ' DST2
else
    echo -e "Ogiltigt alternativ.\nAvslutar script..."
    exit 1
fi

ls "${MNTDIR}"/"${SRC2}"/Users
read -r -p "Välj user katalog som ska backupas " USER

# La till ett mindre känt read-kommando för att lägga till ett radbyte.
# Du kan lägga till \x0a vart som helst på raden för att få till radbyten i ett read-kommando.
# Se bara till att använda enkla cituationstecken samt dollartecken framför.
read -r -p $'\x0aAnge Ordernr ex. UVN20xxxx ' NVN

echo -e "Kommer backupa filer från ${USER} till ${MNTDIR}/backupserver/${DST2}/${NVN}/${USER}\n"

backup_files=( "${MNTDIR}/${SRC2}/Users/${USER}/Desktop"
"${MNTDIR}/${SRC2}/Users/${USER}/Documents"
"${MNTDIR}/${SRC2}/Users/${USER}/Pictures"
"${MNTDIR}/${SRC2}/Users/${USER}/SkyDrive"
"${MNTDIR}/${SRC2}/Users/${USER}/Dropbox"
"${MNTDIR}/${SRC2}/Users/${USER}/Videos"
"${MNTDIR}/${SRC2}/Users/${USER}/SkyDrive"
"${MNTDIR}/${SRC2}/Users/${USER}/Saved Games"
"${MNTDIR}/${SRC2}/Users/${USER}/OneDrive"
"${MNTDIR}/${SRC2}/Users/${USER}/Google Drive"
"${MNTDIR}/${SRC2}/Users/${USER}/Music"
"${MNTDIR}/${SRC2}/Users/${USER}/Favorites"
"${MNTDIR}/${SRC2}/Users/${USER}/Downloads"
"${MNTDIR}/${SRC2}/SIE"
"${MNTDIR}/${SRC2}/ProgramData/SPCS"
"${MNTDIR}/${SRC2}/SPCSFiler"
"${MNTDIR}/${SRC2}/Users/${USER}/AppData/Local/Microsoft/Windows Mail"
"${MNTDIR}/${SRC2}/Users/${USER}/AppData/Local/Microsoft/Outlook"
"${MNTDIR}/${SRC2}/Users/${USER}/AppData/Local/Microsoft/Windows Live Mail"
"${MNTDIR}/${SRC2}/Users/${USER}/AppData/Local/Google/User Data/Default"
"${MNTDIR}/${SRC2}/Users/${USER}/AppData/Roaming/Mozilla/Firefox/Profiles"
"${MNTDIR}/${SRC2}/Users/${USER}/AppData/Roaming/Thunderbird/Profiles" )

target="${MNTDIR}/backupserver/${DST2}/${NVN}/${USER}"
mkdir -p -v "${target}"

echo -e "Backupar standard sakerna som Dokument, skrivbord, favoriter o.sv från ${USER} till ${target}\nSPCS kataloger om dom finns kopieras dessa också."
echo "Kopierar även chrome profile, firefox profil samt thunderbird profiler för bookmarks och mail"

# Anävnder en for loop istället för foreach då jag fick samma problem med "spaces" annars. '#' innan variabelnamnet gör så du får tillbaka
# antalet 'entries' i arrayen och sedan körs rsync-kommandot för varje 'entry'.

for ((i =0; i < ${#backup_files[@]}; i++))
do
    rsync -avuS --progress --numeric-ids --chmod=u=rwX --no-owner --no-perms --no-group -S --numeric-ids "${backup_files[$i]}" "${target}"
done

echo "Backup klar"

exit $?
